version: 2
## Customize the test machine
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    working_directory: ~/wantonwicked
    environment:
      TZ: "/usr/share/zoneinfo/Americas/Los_Angeles"
      APP_ENV: test
    steps:
      - checkout
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      # composer cache
      - restore_cache:
          keys:
            - composer-dependencies-{{ checksum composer.lock }}
            - composer-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-dependencies-{{ checksum composer.lock }}
          paths:
            - vendor
  test:
    docker:
      - image: circleci/php:7.1-apache-jessie-node-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Americas/Los_Angeles"
      APP_ENV: test
    steps:
      - checkout
      - run: echo 127.0.0.1 dev-wanton | sudo tee -a /etc/hosts
      - run:
          name: composer
          command: composer install
      - run: ./vendor/bin/phpunit tests

  deploy_to_prod:
    docker:
      - image: circleci/php:7.1-apache-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Prod Script
          command: ./deploy/deploy_to_prod.sh
  deploy_to_test:
    docker:
      - image: circleci/php:7.1-apache-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Staging Script
          command: echo "Deploy to Test"

workflows:
  version: 2
  deploy_staging:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy_to_test:
          requires:
            - build
  test:
    jobs:
      - test
