version: 2


## Customize the test machine
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-jessie-node-browsers

    environment:
      TZ: "/usr/share/zoneinfo/Americas/Los_Angeles"
      APP_ENV: test

    steps:
      - checkout
      - run: echo 127.0.0.1 dev-wanton | sudo tee -a /etc/hosts
      - run:
        - name: composer
        - command: composer install

workflows:
  version: 2
  deploy_prod:
    jobs:
      - deploy_to_prod
      requires:
        - test
      filters:
        branches:
          only: master

  deploy_staging:
    jobs:
      - deploy_to_test
      requires:
        - test
      filters:
        branches:
          only: develop
  test:
    run:
      - name: phpunit
      - command: vendor/bin/phpunit tests

test:
  override:
    -

deployment:
  staging:
    branch: develop
    commands:
      - ./deploy/deploy_to_test.sh

  prod:
    branch: master
    commands:
      - ./deploy/deploy_to_prod.sh

